Repository be14-fin-Clover-Salad/be14-fin-Clover-Salad-BE, pull requests merged in 2025-06, with the labels that each got.

#143 [Feat] 프론트엔드 백엔드 사이 통신을 위한 개발용 CORS 설정 추가
  src/main/java/com/clover/salad/common/WebConfig.java
  src/main/java/com/clover/salad/security/AuthenticationFilter.java
  src/main/java/com/clover/salad/security/JwtAuthenticationProvider.java
  src/main/java/com/clover/salad/security/JwtFilter.java
  src/main/java/com/clover/salad/security/JwtUtil.java
Labels: enhancement

#144 [Feat] 비밀번호 초기화 기능 구현
  build.gradle
  db/Dummy.sql
  src/main/java/com/clover/salad/common/AppConfig.java
  src/main/java/com/clover/salad/common/WebConfig.java
  src/main/java/com/clover/salad/employee/command/application/controller/EmployeeCommandController.java
  src/main/java/com/clover/salad/employee/command/application/dto/RequestConfirmResetPasswordDTO.java
  src/main/java/com/clover/salad/employee/command/application/dto/RequestResetPasswordDTO.java
  src/main/java/com/clover/salad/employee/command/application/service/EmployeeCommandService.java
  src/main/java/com/clover/salad/employee/command/application/service/EmployeeCommandServiceImpl.java
  src/main/java/com/clover/salad/employee/command/domain/aggregate/entity/EmployeeEntity.java
  src/main/java/com/clover/salad/employee/command/domain/aggregate/enums/EmployeeLevelConverter.java
  src/main/java/com/clover/salad/employee/command/domain/aggregate/vo/RequestLoginVO.java
  src/main/java/com/clover/salad/employee/command/domain/repository/EmployeeRepository.java
  src/main/java/com/clover/salad/employee/query/dto/DepartmentQueryDTO.java
  src/main/java/com/clover/salad/employee/query/service/EmployeeQueryServiceImpl.java
  src/main/java/com/clover/salad/security/AuthService.java
Labels: enhancement

#146 [Refactor] 테이블 VARCHAR 크기 수정
  db/SaladERP.sql
  src/main/java/com/clover/salad/contract/command/dto/ContractUploadRequestDTO.java
  src/main/java/com/clover/salad/contract/command/dto/ProductDTO.java
  src/main/java/com/clover/salad/contract/command/service/PdfContractParserService.java
Labels: enhancement

#145 [Refactor] 고객 조회 기능 수정
  src/main/java/com/clover/salad/common/WebConfig.java
  src/main/java/com/clover/salad/customer/query/controller/CustomerQueryController.java
  src/main/java/com/clover/salad/customer/query/dto/CustomerQueryDTO.java
  src/main/java/com/clover/salad/customer/query/mapper/CustomerMapper.java
  src/main/java/com/clover/salad/customer/query/service/CustomerQueryService.java
  src/main/java/com/clover/salad/customer/query/service/CustomerQueryServiceImpl.java
  src/main/resources/com/clover/salad/customer/query/mapper/CustomerMapper.xml
Labels: enhancement

#148 [Feat] 리프레시 토큰을 통한 액세스 토큰 재발급 기능 구현
  src/main/java/com/clover/salad/common/WebConfig.java
  src/main/java/com/clover/salad/employee/command/application/controller/EmployeeCommandController.java
  src/main/java/com/clover/salad/employee/query/service/EmployeeQueryServiceImpl.java
  src/main/java/com/clover/salad/security/AuthService.java
  src/main/java/com/clover/salad/security/AuthenticationFilter.java
Labels: enhancement

#149 [Feat] 실적 목표 수정/삭제 기능 구현
  src/main/java/com/clover/salad/goal/command/application/controller/GoalCommandController.java
  src/main/java/com/clover/salad/goal/command/application/service/GoalCommandService.java
  src/main/java/com/clover/salad/goal/command/application/service/GoalCommandServiceImpl.java
  src/main/java/com/clover/salad/goal/command/domain/repository/GoalRepository.java
  src/main/java/com/clover/salad/goal/query/controller/GoalQueryController.java
  src/main/java/com/clover/salad/goal/query/mapper/GoalMapper.java
  src/main/java/com/clover/salad/goal/query/service/GoalQueryService.java
  src/main/java/com/clover/salad/goal/query/service/GoalQueryServiceImpl.java
  src/main/resources/com/clover/salad/goal/query/mapper/GoalMapper.xml
Labels: enhancement

#153 [Feat] 계약 상세 조회 기능 구현
  db/ContractDummy.sql
  src/main/java/com/clover/salad/common/WebConfig.java
  src/main/java/com/clover/salad/contract/query/controller/ContractController.java
  src/main/java/com/clover/salad/contract/query/dto/ContractResponseDTO.java
  src/main/java/com/clover/salad/contract/query/dto/ProductDTO.java
  src/main/java/com/clover/salad/contract/query/mapper/ContractMapper.java
  src/main/java/com/clover/salad/contract/query/service/ContractService.java
  src/main/java/com/clover/salad/contract/query/service/ContractServiceImpl.java
  src/main/resources/com/clover/salad/contract/query/mapper/ContractMapper.xml
Labels: enhancement

#160 [Feature] 계약 수정 기능 함수 구현
  src/main/java/com/clover/salad/common/file/entity/FileUploadEntity.java
  src/main/java/com/clover/salad/contract/command/controller/ContractUploadController.java
  src/main/java/com/clover/salad/contract/command/dto/ContractUpdateRequestDTO.java
  src/main/java/com/clover/salad/contract/command/dto/ContractUpdateResponseDTO.java
  src/main/java/com/clover/salad/contract/command/service/ContractService.java
Labels: enhancement

#164 [Feat] 로그인 시 헤더에 표시할 사용자 정보까지 한 번에 조회하는 기능 구현
  src/main/java/com/clover/salad/common/file/entity/FileUploadEntity.java
  src/main/java/com/clover/salad/employee/command/application/controller/AuthController.java
  src/main/java/com/clover/salad/employee/command/application/controller/EmployeeCommandController.java
  src/main/java/com/clover/salad/employee/query/controller/EmployeeQueryController.java
  src/main/java/com/clover/salad/employee/query/dto/LoginHeaderInfoDTO.java
  src/main/java/com/clover/salad/employee/query/dto/LoginResponseDTO.java
  src/main/java/com/clover/salad/employee/query/mapper/EmployeeMapper.java
  src/main/java/com/clover/salad/employee/query/service/EmployeeQueryService.java
  src/main/java/com/clover/salad/employee/query/service/EmployeeQueryServiceImpl.java
  src/main/java/com/clover/salad/security/JwtUtil.java
  src/main/resources/com/clover/salad/employee/query/mapper/EmployeeMapper.xml
Labels: enhancement

#161 [Refactor] 고객 등록/수정/삭제 기능 구현 완료
  build.gradle
  src/main/java/com/clover/salad/common/validation/EmailValidator.java
  src/main/java/com/clover/salad/common/validation/ValidEmail.java
  src/main/java/com/clover/salad/customer/command/application/controller/CustomerCommandController.java
  src/main/java/com/clover/salad/customer/command/application/dto/CustomerCreateRequest.java
  src/main/java/com/clover/salad/customer/command/application/dto/CustomerDTO.java
  src/main/java/com/clover/salad/customer/command/application/dto/CustomerUpdateRequest.java
  src/main/java/com/clover/salad/customer/command/application/service/CustomerCommandService.java
  src/main/java/com/clover/salad/customer/command/application/service/CustomerCommandServiceImpl.java
  src/main/java/com/clover/salad/customer/command/domain/aggregate/entity/Customer.java
  src/main/java/com/clover/salad/customer/command/domain/repository/CustomerRepository.java
  src/main/java/com/clover/salad/customer/query/dto/CustomerQueryDTO.java
  src/test/java/com/clover/salad/common/validation/EmailValidatorTest.java
Labels: enhancement

#159 [Refactor] 토큰으로 현재 사용자를 가져오는 로직 적용
  src/main/java/com/clover/salad/common/exception/EmployeeNotFoundException.java
  src/main/java/com/clover/salad/common/exception/GlobalExceptionHandler.java
  src/main/java/com/clover/salad/common/exception/InvalidSearchTermException.java
  src/main/java/com/clover/salad/common/exception/UnauthorizedEmployeeException.java
  src/main/java/com/clover/salad/goal/command/application/controller/GoalCommandController.java
  src/main/java/com/clover/salad/goal/command/application/dto/DeptSearchTermDTO.java
  src/main/java/com/clover/salad/goal/command/application/dto/EmployeeSearchTermDTO.java
  src/main/java/com/clover/salad/goal/command/application/service/GoalCommandService.java
  src/main/java/com/clover/salad/goal/command/application/service/GoalCommandServiceImpl.java
  src/main/java/com/clover/salad/goal/query/controller/GoalQueryController.java
  src/main/java/com/clover/salad/goal/query/mapper/GoalMapper.java
  src/main/java/com/clover/salad/goal/query/service/GoalQueryService.java
  src/main/java/com/clover/salad/goal/query/service/GoalQueryServiceImpl.java
  src/main/resources/com/clover/salad/goal/query/mapper/GoalMapper.xml
Labels: enhancement

#169 [Feat] 로그인된 사원이 관리자인지 체크하는 기능 구현
  src/main/java/com/clover/salad/employee/command/domain/repository/EmployeeRepository.java
  src/main/java/com/clover/salad/employee/query/mapper/EmployeeMapper.java
  src/main/java/com/clover/salad/employee/query/service/EmployeeQueryService.java
  src/main/java/com/clover/salad/employee/query/service/EmployeeQueryServiceImpl.java
  src/main/resources/com/clover/salad/employee/query/mapper/EmployeeMapper.xml
Labels: enhancement

#177 [Feat] 상담 내역 조회 및 권한별 분기 처리
  src/main/java/com/clover/salad/.DS_Store
  src/main/java/com/clover/salad/consult/query/controller/ConsultQueryController.java
  src/main/java/com/clover/salad/consult/query/dto/ConsultQueryDTO.java
  src/main/java/com/clover/salad/consult/query/mapper/ConsultMapper.java
  src/main/java/com/clover/salad/consult/query/service/ConsultQueryService.java
  src/main/java/com/clover/salad/consult/query/service/ConsultQueryServiceImpl.java
  src/main/resources/com/clover/salad/consult/query/mapper/ConsultMapper.xml
Labels: enhancement

#176 [Feat] 매출 내역 조회 기능 구현
  src/main/java/com/clover/salad/sales/command/domain/aggregate/entity/SalesEntity.java
  src/main/java/com/clover/salad/sales/query/controller/SalesQueryController.java
  src/main/java/com/clover/salad/sales/query/dto/SalesQueryRequestDTO.java
  src/main/java/com/clover/salad/sales/query/dto/SalesQueryResponseDTO.java
  src/main/java/com/clover/salad/sales/query/mapper/SalesQueryMapper.java
  src/main/java/com/clover/salad/sales/query/service/SalesQueryService.java
  src/main/java/com/clover/salad/sales/query/service/SalesQueryServiceImpl.java
  src/main/resources/com/clover/salad/sales/query/mapper/SalesQueryMapper.xml
Labels: enhancement

#182 [Refactor] 로그인 로직 수정 및 식별자 변경
  src/main/java/com/clover/salad/common/exception/AuthException.java
  src/main/java/com/clover/salad/common/exception/GlobalExceptionHandler.java
  src/main/java/com/clover/salad/consult/query/controller/ConsultQueryController.java
  src/main/java/com/clover/salad/consult/query/service/ConsultQueryServiceImpl.java
  src/main/java/com/clover/salad/employee/command/application/controller/EmployeeCommandController.java
  src/main/java/com/clover/salad/employee/command/application/dto/EmployeeUpdateDTO.java
  src/main/java/com/clover/salad/employee/command/application/dto/ResponseChangePasswordDTO.java
  src/main/java/com/clover/salad/employee/command/application/dto/UpdateProfilePathDTO.java
  src/main/java/com/clover/salad/employee/command/application/service/EmployeeCommandService.java
  src/main/java/com/clover/salad/employee/command/application/service/EmployeeCommandServiceImpl.java
  src/main/java/com/clover/salad/employee/command/domain/aggregate/entity/EmployeeEntity.java
  src/main/java/com/clover/salad/employee/query/controller/EmployeeQueryController.java
  src/main/java/com/clover/salad/employee/query/mapper/EmployeeMapper.java
  src/main/java/com/clover/salad/employee/query/service/EmployeeQueryService.java
  src/main/java/com/clover/salad/employee/query/service/EmployeeQueryServiceImpl.java
  src/main/java/com/clover/salad/goal/command/application/controller/GoalCommandController.java
  src/main/java/com/clover/salad/goal/query/controller/GoalQueryController.java
  src/main/java/com/clover/salad/security/AuthenticationFilter.java
  src/main/java/com/clover/salad/security/EmployeeDetails.java
  src/main/java/com/clover/salad/security/JwtAuthenticationProvider.java
  src/main/java/com/clover/salad/security/JwtFilter.java
  src/main/java/com/clover/salad/security/JwtUtil.java
  src/main/java/com/clover/salad/security/SecurityUtil.java
  src/main/java/com/clover/salad/security/WebSecurity.java
  src/main/java/com/clover/salad/security/auth/AuthController.java
  src/main/java/com/clover/salad/security/auth/AuthService.java
  src/main/java/com/clover/salad/security/auth/AuthServiceImpl.java
  src/main/java/com/clover/salad/security/token/TokenPrincipal.java
  src/main/resources/com/clover/salad/employee/query/mapper/EmployeeMapper.xml
Labels: enhancement

#185 [Refactor] 토큰의 사원 코드를 사용하는 로직을 사원 id를 사용하도록 변경
  src/main/java/com/clover/salad/goal/command/application/controller/GoalCommandController.java
  src/main/java/com/clover/salad/goal/command/application/service/GoalCommandService.java
  src/main/java/com/clover/salad/goal/command/application/service/GoalCommandServiceImpl.java
  src/main/java/com/clover/salad/goal/query/controller/GoalQueryController.java
  src/main/java/com/clover/salad/goal/query/mapper/GoalMapper.java
  src/main/java/com/clover/salad/goal/query/service/GoalQueryService.java
  src/main/java/com/clover/salad/goal/query/service/GoalQueryServiceImpl.java
  src/main/resources/com/clover/salad/goal/query/mapper/GoalMapper.xml
Labels: enhancement

#187 [Feat] 매출 등록, 삭제 기능 구현
  src/main/java/com/clover/salad/sales/command/application/controller/SalesCommandController.java
  src/main/java/com/clover/salad/sales/command/application/dto/SalesCommandDTO.java
  src/main/java/com/clover/salad/sales/command/application/mapper/SalesMapper.java
  src/main/java/com/clover/salad/sales/command/application/service/SalesCommandService.java
  src/main/java/com/clover/salad/sales/command/application/service/SalesCommandServiceImpl.java
  src/main/java/com/clover/salad/sales/command/domain/aggregate/entity/SalesEntity.java
  src/main/java/com/clover/salad/sales/command/domain/repository/SalesRepository.java
  src/main/java/com/clover/salad/security/AuthenticationFilter.java
  src/main/java/com/clover/salad/security/JwtFilter.java
  src/main/java/com/clover/salad/security/JwtUtil.java
  src/main/java/com/clover/salad/security/SecurityUtil.java
Labels: enhancement

#189 [Refactor] 계약 조회시 CustomerID 추가
  src/main/java/com/clover/salad/contract/query/controller/ContractController.java
  src/main/java/com/clover/salad/contract/query/dto/ContractDTO.java
  src/main/java/com/clover/salad/contract/query/dto/ContractSearchDTO.java
  src/main/java/com/clover/salad/contract/query/mapper/ContractMapper.java
  src/main/java/com/clover/salad/contract/query/service/ContractService.java
  src/main/java/com/clover/salad/contract/query/service/ContractServiceImpl.java
  src/main/resources/com/clover/salad/contract/query/mapper/ContractMapper.xml
Labels: enhancement

#195 [Feat] 결재 내역 조회 기능 구현
  src/main/java/com/clover/salad/approval/command/domain/aggregate/converter/ApprovalStateConverter.java
  src/main/java/com/clover/salad/approval/command/domain/aggregate/entity/ApprovalEntity.java
  src/main/java/com/clover/salad/approval/command/domain/aggregate/enums/ApprovalState.java
  src/main/java/com/clover/salad/approval/query/controller/ApprovalQueryController.java
  src/main/java/com/clover/salad/approval/query/dto/ApprovalSearchRequestDTO.java
  src/main/java/com/clover/salad/approval/query/dto/ApprovalSearchResponseDTO.java
  src/main/java/com/clover/salad/approval/query/mapper/ApprovalMapper.java
  src/main/java/com/clover/salad/approval/query/service/ApprovalQueryService.java
  src/main/java/com/clover/salad/approval/query/service/ApprovalQueryServiceImpl.java
  src/main/java/com/clover/salad/employee/command/domain/aggregate/entity/EmployeeEntity.java
  src/main/java/com/clover/salad/employee/query/mapper/EmployeeMapper.java
  src/main/java/com/clover/salad/employee/query/service/EmployeeQueryService.java
  src/main/java/com/clover/salad/employee/query/service/EmployeeQueryServiceImpl.java
  src/main/resources/com/clover/salad/approval/query/mapper/ApprovalMapper.xml
  src/main/resources/com/clover/salad/employee/query/mapper/EmployeeMapper.xml
Labels: enhancement

#211 [Feat] 요청한 다른 도메인 조회 구현
  src/main/java/com/clover/salad/contract/query/controller/ContractController.java
  src/main/java/com/clover/salad/contract/query/mapper/ContractMapper.java
  src/main/java/com/clover/salad/contract/query/service/ContractService.java
  src/main/java/com/clover/salad/contract/query/service/ContractServiceImpl.java
  src/main/resources/com/clover/salad/contract/query/mapper/ContractMapper.xml
Labels: enhancement

#216 [Feat] 공지 사항 Command 기능 구현
  src/main/java/com/clover/salad/notice/command/application/controller/NoticeCommandController.java
  src/main/java/com/clover/salad/notice/command/application/dto/NoticeCreateRequest.java
  src/main/java/com/clover/salad/notice/command/application/dto/NoticeUpdateRequest.java
  src/main/java/com/clover/salad/notice/command/application/service/NoticeCommandService.java
  src/main/java/com/clover/salad/notice/command/application/service/NoticeCommandServiceImpl.java
  src/main/java/com/clover/salad/notice/command/domain/aggregate/entity/EmployeeNotice.java
  src/main/java/com/clover/salad/notice/command/domain/aggregate/entity/Notice.java
  src/main/java/com/clover/salad/notice/command/domain/repository/EmployeeNoticeRepository.java
  src/main/java/com/clover/salad/notice/command/domain/repository/NoticeRepository.java
  src/main/java/com/clover/salad/notice/query/dto/NoticeListDTO.java
Labels: enhancement

#217 [Feat] 계약서 양식 등록 구현
  src/main/java/com/clover/salad/common/file/service/LocalFileStorageService.java
  src/main/java/com/clover/salad/documentTemplate/command/application/controller/DocumentTemplateCommandController.java
  src/main/java/com/clover/salad/documentTemplate/command/application/dto/DocumentTemplateUploadRequestDTO.java
  src/main/java/com/clover/salad/documentTemplate/command/application/dto/DocumentTemplateUploadResponseDTO.java
  src/main/java/com/clover/salad/documentTemplate/command/application/service/DocumentTemplateCommandService.java
  src/main/java/com/clover/salad/documentTemplate/command/application/service/DocumentTemplateCommandServiceImpl.java
  src/main/java/com/clover/salad/documentTemplate/command/domain/aggregate/entity/DocumentTemplateEntity.java
  src/main/java/com/clover/salad/documentTemplate/command/domain/repository/DocumentTemplateCommandRepository.java
Labels: enhancement

#221 [Refactor] 누락된 dto 필드 추가
  src/main/java/com/clover/salad/employee/query/dto/EmployeeDetailDTO.java
  src/main/java/com/clover/salad/performance/command/application/controller/PerformanceCommandController.java
  src/main/java/com/clover/salad/performance/command/application/service/PerformanceCommandServiceImpl.java
  src/main/resources/com/clover/salad/employee/query/mapper/EmployeeMapper.xml
Labels: enhancement

#241 [Refactor] 사원 검색 및 모달창 구현을 위한 dto 수정
  src/main/java/com/clover/salad/employee/query/dto/EmployeeDetailDTO.java
  src/main/java/com/clover/salad/employee/query/dto/EmployeeSearchResponseDTO.java
  src/main/java/com/clover/salad/employee/query/dto/LoginHeaderInfoDTO.java
  src/main/java/com/clover/salad/employee/query/service/EmployeeQueryServiceImpl.java
  src/main/resources/com/clover/salad/employee/query/mapper/EmployeeMapper.xml
Labels: enhancement

#229 [Feat] 문의사항 Command 기능 구현
  db/SaladERP.sql
  src/main/java/com/clover/salad/common/exception/BadRequestException.java
  src/main/java/com/clover/salad/common/exception/NotFoundException.java
  src/main/java/com/clover/salad/notice/command/application/controller/NoticeCommandController.java
  src/main/java/com/clover/salad/notice/command/application/service/NoticeCommandServiceImpl.java
  src/main/java/com/clover/salad/notice/query/dto/CheckInfoDTO.java
  src/main/java/com/clover/salad/qna/command/application/controller/QnaCommandController.java
  src/main/java/com/clover/salad/qna/command/application/dto/QnaAnswerRequest.java
  src/main/java/com/clover/salad/qna/command/application/dto/QnaCreateRequest.java
  src/main/java/com/clover/salad/qna/command/application/service/QnaCommandService.java
  src/main/java/com/clover/salad/qna/command/application/service/QnaCommandServiceImpl.java
  src/main/java/com/clover/salad/qna/command/domain/aggregate/entity/Qna.java
  src/main/java/com/clover/salad/qna/command/domain/repository/QnaRepository.java
  src/main/resources/com/clover/salad/notice/query/mapper/NoticeMapper.xml
Labels: enhancement

#233 [Feat] 결재 요청 시 해당 계약이 존재하는지 체크하는 로직 추가
  src/main/java/com/clover/salad/approval/command/application/service/ApprovalCommandServiceImpl.java
Labels: enhancement

#244 [Refactor] 백엔드 api 수정
  db/Dummy.sql
  src/main/java/com/clover/salad/goal/command/application/controller/GoalCommandController.java
  src/main/java/com/clover/salad/goal/query/controller/GoalQueryController.java
  src/main/java/com/clover/salad/performance/command/application/controller/PerformanceCommandController.java
  src/main/java/com/clover/salad/performance/query/controller/PerformanceQueryController.java
  src/main/java/com/clover/salad/product/command/application/controller/ProductCommandController.java
  src/main/java/com/clover/salad/product/query/controller/ProductQueryController.java
Labels: enhancement

#245 [Feat] : 계약서 양식 수정 삭제 조회
  src/main/java/com/clover/salad/contract/document/entity/DocumentTemplate.java
  src/main/java/com/clover/salad/documentTemplate/command/application/controller/DocumentTemplateCommandController.java
  src/main/java/com/clover/salad/documentTemplate/command/application/dto/DocumentTemplateDTO.java
  src/main/java/com/clover/salad/documentTemplate/command/application/dto/DocumentTemplatePatchRequestDTO.java
  src/main/java/com/clover/salad/documentTemplate/command/application/service/DocumentTemplateCommandService.java
  src/main/java/com/clover/salad/documentTemplate/command/application/service/DocumentTemplateCommandServiceImpl.java
  src/main/java/com/clover/salad/documentTemplate/command/domain/repository/DocumentTemplateCommandRepository.java
  src/main/java/com/clover/salad/documentTemplate/query/controller/DocumentTemplateQueryController.java
  src/main/java/com/clover/salad/documentTemplate/query/dto/DocumentTemplateSearchDTO.java
  src/main/java/com/clover/salad/documentTemplate/query/mapper/DocumentTemplateQueryMapper.java
  src/main/java/com/clover/salad/documentTemplate/query/service/DocumentTemplateQueryService.java
  src/main/java/com/clover/salad/documentTemplate/query/service/DocumentTemplateQueryServiceImpl.java
  src/main/resources/com/clover/salad/contract/query/mapper/ContractMapper.xml
  src/main/resources/com/clover/salad/documentTemplate/query/mapper/DocumentTemplateQueryMapper.xml
Labels: enhancement

#248 [Feat] 상품 이미지 등록/조회 기능 추가
  src/main/java/com/clover/salad/product/command/application/controller/ProductCommandController.java
  src/main/java/com/clover/salad/product/command/application/dto/ProductDTO.java
  src/main/java/com/clover/salad/product/command/application/dto/ProductImageDTO.java
  src/main/java/com/clover/salad/product/command/application/service/ProductCommandService.java
  src/main/java/com/clover/salad/product/command/application/service/ProductCommandServiceImpl.java
  src/main/java/com/clover/salad/product/query/controller/ProductQueryController.java
  src/main/resources/com/clover/salad/product/query/mapper/ProductMapper.xml
Labels: enhancement

#254 [Refactor] 고객 지원 관련 쿼리문 및 더미 데이터 수정
  db/Dummy.sql
  src/main/resources/com/clover/salad/notice/query/mapper/NoticeMapper.xml
Labels: enhancement

#259 [Feat] 영업별 매출 대시보드 기능 구현
  db/Dummy.sql
  src/main/java/com/clover/salad/salesDashboard/query/controller/SalesDashboardQueryController.java
  src/main/java/com/clover/salad/salesDashboard/query/dto/SalesMonthlyTrendResponseDTO.java
  src/main/java/com/clover/salad/salesDashboard/query/dto/SalesQuarterlyTrendResponseDTO.java
  src/main/java/com/clover/salad/salesDashboard/query/dto/SalesTeamAmountResponseDTO.java
  src/main/java/com/clover/salad/salesDashboard/query/dto/SalesTeamRatioRawDTO.java
  src/main/java/com/clover/salad/salesDashboard/query/dto/SalesTeamRatioResponseDTO.java
  src/main/java/com/clover/salad/salesDashboard/query/dto/SalesTotalRequestDTO.java
  src/main/java/com/clover/salad/salesDashboard/query/dto/SalesTotalResponseDTO.java
  src/main/java/com/clover/salad/salesDashboard/query/dto/SalesYearlyTrendResponseDTO.java
  src/main/java/com/clover/salad/salesDashboard/query/mapper/SalesDashboardQueryMapper.java
  src/main/java/com/clover/salad/salesDashboard/query/service/SalesDashboardQueryService.java
  src/main/java/com/clover/salad/salesDashboard/query/service/SalesDashboardQueryServiceImpl.java
  src/main/java/com/clover/salad/security/WebSecurity.java
  src/main/resources/com/clover/salad/salesDashboard/query/mapper/SalesDashboardQueryMapper.xml
Labels: enhancement

#262 [Env] Validator 추가
  src/main/java/com/clover/salad/common/validator/BirthdateValidator.java
  src/main/java/com/clover/salad/common/validator/EmailValidator.java
  src/main/java/com/clover/salad/common/validator/PhoneValidator.java
  src/main/java/com/clover/salad/common/validator/ValidBirthdate.java
  src/main/java/com/clover/salad/common/validator/ValidEmail.java
  src/main/java/com/clover/salad/common/validator/ValidPhone.java
  src/main/java/com/clover/salad/customer/command/application/dto/CustomerCreateRequest.java
  src/test/java/com/clover/salad/common/validation/EmailValidatorTest.java
Labels: enhancement

#263 공지사항, 문의사항 등록 시 알림 생성 기능 추가
  db/Dummy.sql
  src/main/java/com/clover/salad/employee/query/mapper/EmployeeMapper.java
  src/main/java/com/clover/salad/notice/command/application/service/NoticeCommandServiceImpl.java
  src/main/java/com/clover/salad/qna/command/application/service/QnaCommandServiceImpl.java
  src/main/resources/com/clover/salad/employee/query/mapper/EmployeeMapper.xml
Labels: enhancement

#261 [Feat] : AWS S3 버킷 파일 업로드 함수 구현
  build.gradle
  db/SaladERP.sql
  src/main/java/com/clover/salad/common/file/config/S3Config.java
  src/main/java/com/clover/salad/common/file/controller/FileUploadController.java
  src/main/java/com/clover/salad/common/file/dto/FileUploadResultDTO.java
  src/main/java/com/clover/salad/common/file/entity/FileUploadEntity.java
  src/main/java/com/clover/salad/common/file/enums/FileUploadType.java
  src/main/java/com/clover/salad/common/file/repository/FileUploadRepository.java
  src/main/java/com/clover/salad/common/file/service/FileUploadService.java
  src/main/java/com/clover/salad/common/file/service/LocalFileStorageService.java
  src/main/java/com/clover/salad/common/file/service/S3PathResolver.java
  src/main/java/com/clover/salad/common/file/service/S3Uploader.java
  src/main/java/com/clover/salad/contract/document/service/DocumentOriginService.java
Labels: enhancement

#270 [Feat] 상담 내역 등록
  src/main/java/com/clover/salad/common/exception/GlobalExceptionHandler.java
  src/main/java/com/clover/salad/common/util/AuthUtil.java
  src/main/java/com/clover/salad/common/validator/BirthdateValidator.java
  src/main/java/com/clover/salad/common/validator/PhoneValidator.java
  src/main/java/com/clover/salad/common/validator/ValidBirthdate.java
  src/main/java/com/clover/salad/consult/command/application/controller/ConsultationCommandController.java
  src/main/java/com/clover/salad/consult/command/application/dto/ConsultationCreateRequest.java
  src/main/java/com/clover/salad/consult/command/application/service/ConsultationCommandService.java
  src/main/java/com/clover/salad/consult/command/application/service/ConsultationCommandServiceImpl.java
  src/main/java/com/clover/salad/consult/command/domain/aggregate/entity/Consultation.java
  src/main/java/com/clover/salad/consult/command/domain/repository/ConsultationRepository.java
  src/main/java/com/clover/salad/contract/command/dto/CustomerDTO.java
  src/main/java/com/clover/salad/contract/command/service/ContractService.java
  src/main/java/com/clover/salad/contract/command/service/parser/DefaultTemplateParser.java
  src/main/java/com/clover/salad/contract/common/CustomerType.java
  src/main/java/com/clover/salad/customer/command/application/controller/CustomerCommandController.java
  src/main/java/com/clover/salad/customer/command/application/dto/CustomerCreateRequest.java
  src/main/java/com/clover/salad/customer/command/application/dto/CustomerUpdateRequest.java
  src/main/java/com/clover/salad/customer/command/application/service/CustomerCommandService.java
  src/main/java/com/clover/salad/customer/command/application/service/CustomerCommandServiceImpl.java
  src/main/java/com/clover/salad/customer/command/domain/aggregate/entity/Customer.java
  src/main/java/com/clover/salad/customer/command/domain/aggregate/vo/CustomerType.java
  src/main/java/com/clover/salad/customer/command/domain/aggregate/vo/CustomerTypeConverter.java
  src/main/java/com/clover/salad/customer/command/domain/repository/CustomerRepository.java
  src/main/java/com/clover/salad/customer/query/dto/CustomerQueryDTO.java
  src/main/java/com/clover/salad/customer/query/mapper/CustomerMapper.java
  src/main/java/com/clover/salad/customer/query/service/CustomerQueryService.java
  src/main/java/com/clover/salad/customer/query/service/CustomerQueryServiceImpl.java
  src/main/resources/com/clover/salad/customer/query/mapper/CustomerMapper.xml
Labels: enhancement

#272 enum 타입 변경에 맞춰 더미 수정 및 사원 프로필 업데이트 기능에 S3 저장 로직 반영해 프로필을 S3에 저장하도록 구현
  db/Dummy.sql
  db/SaladERP.sql
  src/main/java/com/clover/salad/common/file/controller/FileUploadController.java
  src/main/java/com/clover/salad/common/file/dto/FileUploadResultDTO.java
  src/main/java/com/clover/salad/employee/command/application/controller/EmployeeCommandController.java
  src/main/java/com/clover/salad/employee/command/application/dto/UpdateProfileFileDTO.java
  src/main/java/com/clover/salad/employee/command/application/service/EmployeeCommandService.java
  src/main/java/com/clover/salad/employee/command/application/service/EmployeeCommandServiceImpl.java
  src/main/java/com/clover/salad/employee/query/mapper/EmployeeMapper.java
  src/main/resources/com/clover/salad/employee/query/mapper/EmployeeMapper.xml
Labels: enhancement

#276 [Feat] 결재 연동 계약 상태 동기화 및 SSE 알림 누락 방지 개선
  src/main/java/com/clover/salad/approval/command/application/controller/ApprovalCommandController.java
  src/main/java/com/clover/salad/approval/command/application/dto/ApprovalDecisionDTO.java
  src/main/java/com/clover/salad/approval/command/application/service/ApprovalCommandServiceImpl.java
  src/main/java/com/clover/salad/approval/command/domain/repository/ApprovalRepository.java
  src/main/java/com/clover/salad/approval/query/dto/ApprovalDetailDTO.java
  src/main/java/com/clover/salad/contract/command/entity/ContractEntity.java
  src/main/java/com/clover/salad/contract/common/ContractStatus.java
  src/main/java/com/clover/salad/employee/command/application/service/EmployeeCommandServiceImpl.java
  src/main/java/com/clover/salad/employee/query/controller/DepartmentQueryController.java
  src/main/java/com/clover/salad/employee/query/controller/EmployeeQueryController.java
  src/main/java/com/clover/salad/employee/query/service/EmployeeQueryService.java
  src/main/java/com/clover/salad/employee/query/service/EmployeeQueryServiceImpl.java
  src/main/java/com/clover/salad/notification/query/sse/SseEmitterManager.java
Labels: enhancement

#280 [Env] GitActions 및 CI/CD 설정
  .ebextensions/app.config
  .github/workflows/prod-deploy.yml
  .gitignore
  .platform/nginx.conf
  Procfile
  build.gradle
Labels: enhancement

#277 [Refactor] 계약 업로드 S3 방식으로 수정
  src/main/java/com/clover/salad/common/file/service/FileUploadService.java
  src/main/java/com/clover/salad/common/file/service/S3Uploader.java
  src/main/java/com/clover/salad/contract/command/facade/ContractUploadFacade.java
  src/main/java/com/clover/salad/contract/command/service/ContractService.java
  src/main/java/com/clover/salad/contract/command/service/parser/PdfContractParserService.java
  src/main/java/com/clover/salad/contract/document/service/DocumentOriginService.java
Labels: enhancement

#278 [Feat] 상담 내역 수정
  src/main/java/com/clover/salad/common/validator/EmailValidator.java
  src/main/java/com/clover/salad/consult/command/application/controller/ConsultationCommandController.java
  src/main/java/com/clover/salad/consult/command/application/dto/ConsultationUpdateRequest.java
  src/main/java/com/clover/salad/consult/command/application/service/ConsultationCommandService.java
  src/main/java/com/clover/salad/consult/command/application/service/ConsultationCommandServiceImpl.java
  src/main/java/com/clover/salad/consult/command/domain/aggregate/entity/Consultation.java
  src/main/java/com/clover/salad/consult/command/domain/repository/ConsultationRepository.java
  src/main/java/com/clover/salad/customer/command/application/dto/CustomerUpdateRequest.java
  src/main/java/com/clover/salad/customer/command/application/service/CustomerCommandServiceImpl.java
  src/main/java/com/clover/salad/customer/command/domain/aggregate/entity/Customer.java
  src/main/java/com/clover/salad/customer/command/domain/aggregate/vo/CustomerType.java
  src/main/java/com/clover/salad/customer/query/dto/CustomerQueryDTO.java
Labels: enhancement

#283 [Refactor] 실적 목표 프론트엔드 진행 중 수정사항
  src/main/java/com/clover/salad/goal/command/application/controller/GoalCommandController.java
  src/main/java/com/clover/salad/goal/command/application/dto/EmployeeSearchTermDTO.java
  src/main/java/com/clover/salad/goal/command/application/dto/GoalDTO.java
  src/main/java/com/clover/salad/goal/command/application/service/GoalCommandServiceImpl.java
  src/main/java/com/clover/salad/goal/query/controller/GoalQueryController.java
  src/main/java/com/clover/salad/goal/query/service/GoalQueryService.java
  src/main/java/com/clover/salad/goal/query/service/GoalQueryServiceImpl.java
  src/main/resources/com/clover/salad/goal/query/mapper/GoalMapper.xml
Labels: enhancement

#291 [Env]프론트 CORS 설정 추가
  src/main/java/com/clover/salad/common/WebConfig.java
Labels: enhancement

#290 [Chore] 고객, 상담 더미 수정
  db/Dummy.sql
Labels: enhancement

#287 [Refactor] 고객 삭제 기능 추가 및 PR 반영
  src/main/java/com/clover/salad/customer/command/application/controller/CustomerCommandController.java
  src/main/java/com/clover/salad/customer/command/application/service/CustomerCommandService.java
  src/main/java/com/clover/salad/customer/command/application/service/CustomerCommandServiceImpl.java
  src/main/java/com/clover/salad/customer/command/domain/aggregate/entity/Customer.java
Labels: enhancement

#294 [Refactor] 결재 관련 로직 버그 수정 및 테스트 코드 작성 중
  build.gradle
  db/Dummy.sql
  db/SaladERP.sql
  src/main/java/com/clover/salad/approval/command/application/service/ApprovalCommandServiceImpl.java
  src/main/java/com/clover/salad/common/exception/DuplicateApprovalRequestException.java
  src/main/java/com/clover/salad/common/exception/GlobalExceptionHandler.java
  src/main/java/com/clover/salad/employee/command/domain/aggregate/converter/EmployeeLevelConverter.java
  src/main/java/com/clover/salad/employee/command/domain/aggregate/entity/EmployeeEntity.java
  src/main/java/com/clover/salad/security/WebSecurity.java
  src/main/resources/com/clover/salad/approval/query/mapper/ApprovalMapper.xml
  src/test/java/com/clover/salad/approval/command/application/controller/ApprovalCommandControllerTest.java
  src/test/java/com/clover/salad/employee/command/application/controller/EmployeeCommandControllerTest.java
  src/test/java/com/clover/salad/employee/query/controller/DepartmentQueryControllerTest.java
  src/test/java/com/clover/salad/employee/query/controller/EmployeeQueryControllerTest.java
  src/test/java/com/clover/salad/security/auth/AuthControllerTest.java
  src/test/java/com/clover/salad/security/auth/AuthLoginIntegrationTest.java
Labels: bug, enhancement

#295 [Refactor] 상담 조회 권한 분기 처리
  db/Dummy.sql
  src/main/java/com/clover/salad/common/exception/ConsultsException.java
  src/main/java/com/clover/salad/consult/query/controller/ConsultQueryController.java
  src/main/java/com/clover/salad/consult/query/mapper/ConsultMapper.java
  src/main/java/com/clover/salad/consult/query/service/ConsultQueryService.java
  src/main/java/com/clover/salad/consult/query/service/ConsultQueryServiceImpl.java
  src/main/resources/com/clover/salad/consult/query/mapper/ConsultMapper.xml
Labels: enhancement

#298 [Feat] 고객지원 파트 더미 데이터 수정
  db/Dummy.sql
  db/SaladERP.sql
Labels: enhancement

#296 [Refactor] : 계약 반려 적용
  src/main/java/com/clover/salad/approval/command/application/service/ApprovalCommandServiceImpl.java
  src/main/java/com/clover/salad/documentTemplate/command/application/service/DocumentTemplateCommandServiceImpl.java
Labels: enhancement

#299 [Refactor] 상담/고객 프론트 연결
  src/main/java/com/clover/salad/common/util/AuthUtil.java
  src/main/java/com/clover/salad/consult/query/mapper/ConsultMapper.java
  src/main/java/com/clover/salad/consult/query/service/ConsultQueryService.java
  src/main/java/com/clover/salad/consult/query/service/ConsultQueryServiceImpl.java
  src/main/java/com/clover/salad/customer/query/controller/CustomerQueryController.java
  src/main/java/com/clover/salad/customer/query/mapper/CustomerMapper.java
  src/main/java/com/clover/salad/customer/query/service/CustomerQueryService.java
  src/main/java/com/clover/salad/customer/query/service/CustomerQueryServiceImpl.java
  src/main/resources/com/clover/salad/consult/query/mapper/ConsultMapper.xml
  src/main/resources/com/clover/salad/customer/query/mapper/CustomerMapper.xml
Labels: enhancement

#301 Feat : 계약서 양식 버그 수정 및 썸네일등록
  src/main/java/com/clover/salad/common/file/entity/FileUploadEntity.java
  src/main/java/com/clover/salad/common/file/enums/FileUploadType.java
  src/main/java/com/clover/salad/common/file/service/S3PathResolver.java
  src/main/java/com/clover/salad/documentTemplate/command/application/dto/DocumentTemplateDTO.java
  src/main/java/com/clover/salad/documentTemplate/command/application/service/DocumentTemplateCommandServiceImpl.java
  src/main/resources/com/clover/salad/documentTemplate/query/mapper/DocumentTemplateQueryMapper.xml
Labels: enhancement

#304 [Refactor] 상품 등록 시 이미지를 S3에 업로드하도록 기능 수정 및 상품 수정, 삭제 관리자 권한으로만 할 수 있도록 제약 추가
  src/main/java/com/clover/salad/common/file/service/FileUploadService.java
  src/main/java/com/clover/salad/product/command/application/controller/ProductCommandController.java
  src/main/java/com/clover/salad/product/command/application/service/ProductCommandService.java
  src/main/java/com/clover/salad/product/command/application/service/ProductCommandServiceImpl.java
Labels: enhancement

#305 [Refactor] 상담 관리 프론트 연결을 위한 로직 수정
  src/main/java/com/clover/salad/consult/command/application/controller/ConsultationCommandController.java
  src/main/java/com/clover/salad/consult/query/controller/ConsultQueryController.java
  src/main/java/com/clover/salad/consult/query/dto/ConsultQueryDTO.java
  src/main/java/com/clover/salad/consult/query/mapper/ConsultMapper.java
  src/main/java/com/clover/salad/consult/query/service/ConsultQueryService.java
  src/main/java/com/clover/salad/consult/query/service/ConsultQueryServiceImpl.java
  src/main/resources/com/clover/salad/consult/query/mapper/ConsultMapper.xml
Labels: enhancement

#307 Chore: 실적 목표 관련 더미 데이터 추가로 인한 테이블 수정
  db/SaladERP.sql
Labels: bug

#312 [Feat] 결재 조회 테스트 케이스 추가
  src/test/java/com/clover/salad/approval/query/controller/ApprovalQueryControllerTest.java
Labels: enhancement

#318 [Refactor] 알림 - sse 연결 에러 수정 및 배포 환경에 맞게 cors 정책 수정
  src/main/java/com/clover/salad/common/WebConfig.java
  src/main/java/com/clover/salad/notification/query/controller/NotificationQueryController.java
  src/main/java/com/clover/salad/notification/query/mapper/NotificationMapper.java
  src/main/java/com/clover/salad/notification/query/service/NotificationQueryService.java
  src/main/java/com/clover/salad/notification/query/service/NotificationQueryServiceImpl.java
  src/main/java/com/clover/salad/notification/query/sse/SseEmitterManager.java
  src/main/java/com/clover/salad/security/WebSecurity.java
  src/main/resources/com/clover/salad/notification/query/mapper/NotificationMapper.xml
Labels: bug

#316 [Refactor] 상품 상세 조회 기능 개선
  db/Dummy.sql
  src/main/java/com/clover/salad/product/query/service/ProductQueryServiceImpl.java
  src/main/resources/com/clover/salad/product/query/mapper/ProductMapper.xml
Labels: enhancement

#319 [refactor] 더미수정
  db/Dummy.sql
Labels: enhancement

#320 [Feat] : 관리자일때 계약 전체 보기 함수 구현
  src/main/java/com/clover/salad/common/WebConfig.java
  src/main/java/com/clover/salad/contract/query/dto/ContractSearchDTO.java
  src/main/java/com/clover/salad/contract/query/mapper/ContractMapper.java
  src/main/java/com/clover/salad/contract/query/service/ContractServiceImpl.java
  src/main/java/com/clover/salad/security/WebSecurity.java
  src/main/resources/com/clover/salad/contract/query/mapper/ContractMapper.xml
Labels: enhancement

#322 [Refactor] sse 알림의 연결이 배포환경에서 유지되지 않는 문제 수정
  src/main/java/com/clover/salad/notification/query/sse/SseEmitterManager.java
Labels: enhancement

#324 [Task] 모든 권한용 고객 전체 조회
  src/main/java/com/clover/salad/customer/query/mapper/CustomerMapper.java
  src/main/java/com/clover/salad/customer/query/service/CustomerQueryService.java
  src/main/java/com/clover/salad/customer/query/service/CustomerQueryServiceImpl.java
Labels: enhancement

#326 [Feat] : 계약서 원본 서비스 계층 테스트 케이스 작성
  src/test/java/com/clover/salad/contract/document/service/DocumentOriginServiceTest.java
Labels: enhancement

#327 [Refactor] sse 연결 문제 개선 및 매출 등록 시 계약 존재하지 않는 경우 예외처리
  src/main/java/com/clover/salad/approval/command/application/service/ApprovalCommandServiceImpl.java
  src/main/java/com/clover/salad/notification/command/application/service/NotificationTokenService.java
  src/main/java/com/clover/salad/notification/query/controller/NotificationSseController.java
  src/main/java/com/clover/salad/sales/command/application/service/SalesCommandServiceImpl.java
Labels: enhancement

#331 [Task] 권한 미체크 상담 내역 조회
  src/main/java/com/clover/salad/consult/query/service/ConsultQueryService.java
  src/main/java/com/clover/salad/consult/query/service/ConsultQueryServiceImpl.java
Labels: enhancement

#330 [Feat] 공지사항 서비스 계층 테스트 케이스 작성
  src/main/java/com/clover/salad/notice/command/application/service/NoticeCommandServiceImpl.java
  src/test/java/com/clover/salad/notice/command/application/service/NoticeCommandServiceImplTest.java
  src/test/java/com/clover/salad/notice/query/service/NoticeQueryServiceImplTest.java
Labels: enhancement

#332 [Refactor] 개인 실적 목표 갱신에 권한 필요 없는 메소드 사용하도록 변경
  src/main/java/com/clover/salad/performance/command/application/service/PerformanceCommandServiceImpl.java
Labels: enhancement

#333 [Fix] 상담 목록 조건 수정
  src/main/java/com/clover/salad/performance/command/application/service/PerformanceCommandServiceImpl.java
Labels: bug

#345 [Refactor] 실적 목표 QA 적용
  src/main/java/com/clover/salad/goal/command/application/service/GoalCommandServiceImpl.java
  src/main/java/com/clover/salad/goal/query/controller/GoalQueryController.java
Labels: enhancement

#346 [Feat] 문의사항 서비스 계층 테스트 케이스 작성
  src/test/java/com/clover/salad/qna/command/application/service/QnaCommandServiceImplTest.java
  src/test/java/com/clover/salad/qna/query/service/QnaQueryServiceImplTest.java
Labels: enhancement

#343 [Feat] 사원, 시큐리티 테스트 코드 작성
  src/test/java/com/clover/salad/common/validation/EmailValidatorTest.java
Labels: enhancement

#349 [Refactor] 고객 수정, 삭제 권한 분기 제거
  src/main/java/com/clover/salad/customer/command/application/service/CustomerCommandServiceImpl.java
Labels: enhancement

#350 [Task] 고객/상담 테스트 케이스 작성
  .github/workflows/prod-deploy.yml
  src/test/java/com/clover/salad/consult/command/application/service/ConsultationCommandServiceImplTest.java
  src/test/java/com/clover/salad/consult/query/service/ConsultQueryServiceImplTest.java
  src/test/java/com/clover/salad/customer/command/application/service/CustomerCommandServiceImplTest.java
  src/test/java/com/clover/salad/customer/query/service/CustomerQueryServiceImplTest.java
Labels: enhancement

#351 [Test] 실적, 실적 목표, 상품 테스트 케이스 작성
  src/test/java/com/clover/salad/goal/command/application/service/GoalCommandServiceImplTest.java
  src/test/java/com/clover/salad/goal/query/service/GoalQueryServiceImplTest.java
  src/test/java/com/clover/salad/performance/command/application/service/PerformanceCommandServiceImplTest.java
  src/test/java/com/clover/salad/performance/query/service/PerformanceQueryServiceImplTest.java
  src/test/java/com/clover/salad/product/command/application/service/ProductCommandServiceImplTest.java
  src/test/java/com/clover/salad/product/query/service/ProductQueryServiceImplTest.java
Labels: enhancement

#352 [Refactor] 고객 삭제 테스트 케이스 수정
  src/test/java/com/clover/salad/customer/command/application/service/CustomerCommandServiceImplTest.java
Labels: bug
