Repository be14-fin-Clover-Salad/be14-fin-Clover-Salad-BE, pull requests merged in 2025-05, with the labels that each got.

#20 [Env] 깃허브 AiReview 설정
  .github/workflows/cr.yml
Labels: enhancement

#19 [Fix] 고객 테이블의 'birthdate' 컬럼 제약 조건 수정
  db/SaladERP.sql
Labels: bug

#21 [Chore] 고객 테이블 더미 데이터 추가
  db/DummyCustomers.sql
  gradlew
Labels: enhancement

#23 [Env] gpt 프롬프트 수정
  .github/workflows/cr.yml
Labels: enhancement

#24 [Env] 이슈, PR 템플릿 추가
  .github/ISSUE_TEMPLATE/feature-템플릿.md
  .github/ISSUE_TEMPLATE/hotfix-템플릿.md
  .github/ISSUE_TEMPLATE/refactor-템플릿.md
  .github/PULL_REQUEST_TEMPLATE.md
  .gitignore
Labels: enhancement

#27 [Feat] 상품 수정/삭제 기능 구현
  src/main/java/com/clover/salad/product/command/application/controller/ProductCommandController.java
  src/main/java/com/clover/salad/product/command/application/service/ProductCommandService.java
  src/main/java/com/clover/salad/product/command/application/service/ProductCommandServiceImpl.java
Labels: enhancement

#32 [Env] PR 템플릿 아이콘 변경
  .github/PULL_REQUEST_TEMPLATE.md
Labels: enhancement

#30 [Feat] 고객 목록/상세 조회 기능 구현
  .vscode/settings.json
  bin/main/com/clover/salad/common/temp.txt
  bin/main/com/clover/salad/customer/query/mapper/CustomerMapper.xml
  bin/main/com/clover/salad/product/query/mapper/ProductMapper.xml
  src/main/java/com/clover/salad/SaladApplication.java
  src/main/java/com/clover/salad/customer/command/application/controller/CustomerCommandController.java
  src/main/java/com/clover/salad/customer/command/application/dto/CustomerDTO.java
  src/main/java/com/clover/salad/customer/command/application/service/CustomerCommandService.java
  src/main/java/com/clover/salad/customer/command/application/service/CustomerCommandServiceImpl.java
  src/main/java/com/clover/salad/customer/command/domain/aggregate/entity/Customer.java
  src/main/java/com/clover/salad/customer/command/domain/repository/CustomerRepository.java
  src/main/java/com/clover/salad/customer/query/controller/CustomerQueryController.java
  src/main/java/com/clover/salad/customer/query/mapper/CustomerMapper.java
  src/main/java/com/clover/salad/customer/query/service/CustomerQueryService.java
  src/main/java/com/clover/salad/customer/query/service/CustomerQueryServiceImpl.java
  src/main/resources/com/clover/salad/customer/query/mapper/CustomerMapper.xml
Labels: enhancement

#33 [Env] AiReview 프롬프트 수정
  .github/workflows/cr.yml
Labels: enhancement

#128 [Feat] employee 테이블 관련 db 제약조건 변경사항 업데이트
  db/SaladERP.sql
Labels: enhancement

#126 [Feat] 사원별, 팀별 실적 목표 조회 기능 구현
  db/SaladERP.sql
  src/main/java/com/clover/salad/goal/command/application/dto/GoalDTO.java
  src/main/java/com/clover/salad/goal/command/application/dto/SearchTermDTO.java
  src/main/java/com/clover/salad/goal/query/controller/GoalQueryController.java
  src/main/java/com/clover/salad/goal/query/mapper/GoalMapper.java
  src/main/java/com/clover/salad/goal/query/service/GoalQueryService.java
  src/main/java/com/clover/salad/goal/query/service/GoalQueryServiceImpl.java
  src/main/resources/com/clover/salad/goal/query/mapper/GoalMapper.xml
Labels: enhancement

#130 [Feat] 사원 전체 조회, 조건으로 검색 기능 구현
  db/Dummy.sql
  src/main/java/com/clover/salad/employee/command/domain/aggregate/entity/DepartmentEntity.java
  src/main/java/com/clover/salad/employee/command/domain/aggregate/entity/EmployeeEntity.java
  src/main/java/com/clover/salad/employee/command/domain/aggregate/entity/FileUploadEntity.java
  src/main/java/com/clover/salad/employee/command/domain/aggregate/enums/EmployeeLevel.java
  src/main/java/com/clover/salad/employee/command/domain/aggregate/enums/EmployeeLevelConverter.java
  src/main/java/com/clover/salad/employee/query/controller/EmployeeQueryController.java
  src/main/java/com/clover/salad/employee/query/dto/DepartmentQueryDTO.java
  src/main/java/com/clover/salad/employee/query/dto/EmployeeQueryDTO.java
  src/main/java/com/clover/salad/employee/query/dto/SearchEmployeeDTO.java
  src/main/java/com/clover/salad/employee/query/mapper/EmployeeMapper.java
  src/main/java/com/clover/salad/employee/query/service/EmployeeQueryService.java
  src/main/java/com/clover/salad/employee/query/service/EmployeeQueryServiceImpl.java
  src/main/resources/com/clover/salad/employee/query/mapper/EmployeeMapper.xml
Labels: enhancement

#133 [Style] Dummy.sql 정리
  db/Dummy.sql
Labels: enhancement

#136 [Env] 결재 코드에 unique 제약 조건 추가
  db/SaladERP.sql
Labels: invalid
